---
title: "hierNest"
output: html_document
date: "2026-03-20"
---


```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
library(hierNest)
```

# hierNest

The `hierNest` package allows for fitting of penalized GLMs with covariate 
effects that vary by discrete and hierarchically-organized groups...

## Example
```{r example_data}
data("example_data")
str(example_data)
```

```{r cv_fit, cache = TRUE}
cv.fit <- cv.hierNest(example_data$X,
                      example_data$Y,
                      method       = "overlapping",
                      hier_info    = example_data$hier_info,
                      family       = "binomial",
                      partition    = "subgroup",
                      cvmethod     = "grid_search",
                      asparse1     = c(0.5, 20),
                      asparse2     = c(0.05, 0.20),
                      asparse1_num = 3,
                      asparse2_num = 3,
                      nlambda      = 50)
```

## Coefficient plot
```{r coef_plot}
plot(cv.fit, type = "coefficients")
```

## Subgroup effects
```{r subgroup_plot}
plot(cv.fit, type = "Subgroup effects")
```






